
trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - main

jobs:
  - job: BuildAndLintAndroid
    displayName: 'Build And Lint Android'
    pool:
      name: 'Default'
      vmImage: 'Yosifs-Macbook-Pro'


    variables:
      JAVA_HOME: '/Users/yosif/Library/Java/JavaVirtualMachines/openjdk-22.0.2/Contents/Home'
      ANDROID_HOME: '/usr/local/lib/android/sdk'
      GRADLE_USER_HOME: $(System.DefaultWorkingDirectory)/.gradle

    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          echo "##vso[task.setvariable variable=JAVA_HOME]$(readlink -f /usr/bin/java | sed 's:/bin/java::')"
        displayName: 'Install Java 11'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - task: UseNode@1
        inputs:
          versionSpec: '14.x'
          checkLatest: true

      - script: |
          mkdir -p $ANDROID_HOME
          curl -o sdk-tools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip sdk-tools-linux.zip -d $ANDROID_HOME
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.2"
        displayName: 'Install Android SDK Components'


      - script: |
          echo "Setting up Gradle cache"
          mkdir -p $(GRADLE_USER_HOME)
          chown -R $(id -u):$(id -g) $(GRADLE_USER_HOME)
        displayName: 'Setup Gradle Cache'

      - script: ./gradlew dependencies
        displayName: 'Install Dependencies'

      - script: ./gradlew lint
        displayName: 'Run Lint Check'

      - script: ./gradlew build
        displayName: 'Build Android'

  - job: BuildAndLintIos
    displayName: 'Build and Lint iOS'
    pool:
      name: 'Default'
      vmImage: 'Yosifs-Macbook-Pro'


    steps:
      - script: |
          /usr/libexec/java_home -v 11
          export JAVA_HOME=$(/usr/libexec/java_home -v 11)
          export PATH=$JAVA_HOME/bin:$PATH
        displayName: 'Set up Java 11'

      - script: ./gradlew iosX64Test
        displayName: 'Run iOS Tests'

      - script: ./gradlew assemble
        displayName: 'Build iOS'